---
title: "R Notebook"
output: html_notebook
---

```{r}
session_count <- read.csv("~/Downloads/session_count.csv")
```

```{r}
diff_1 = diff(session_count$sessions)
diff_1_7 = diff(diff(session_count$sessions), 7)
diff_1_4 = diff(diff(session_count$sessions), 4)
```

```{r}
library(tidyr)
library(dplyr)
library(forecast)
```

```{r}
plot(diff(diff(session_count$sessions, 7),4), type="l")
lines(diff(diff(session_count$sessions, 7),3), col="red")
```

```{r}
library(LSTS)
```

```{r}
periods = smooth.periodogram(diff(session_count$sessions))
```

```{r}
peaks_indices = c(which.max(periods$smooth.periodogram), which.max(periods$smooth.periodogram[200:1000]) + 200)
```

```{r}
2*pi/periods$lambda[peaks_indices ]
```

```{r}
plot(diff(session_count$sessions), type="l")
plot(diff(diff(session_count$sessions), 7),type="l")
```

```{r}
par(mfrow=c(1,2))
y = diff(session_count$sessions)[200:250]
x = 1:length(y)/7
plot(x, y,, type="l")

y = diff(session_count$sessions)[550:650]
x = 1:length(y)/7
plot(x, y,, type="l")
```


```{r}
auto_model = auto.arima(session_count$sessions)
```


```{r}
plot(session_count$sessions, type="l")
lines(auto_model$fitted, col="blue")
```

